<?php

/**
 * Countdown milestones: each has a unique visual theme for export.
 * Keys are stable for DB + URLs.
 */
return [
    'milestones' => [
        '365' => [
            'label' => '365 days to go',
            'headline' => '365',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'misty_dusk',
            'quote' => 'Every day closer is another page of your love story waiting to be written.',
        ],
        '100' => [
            'label' => '100 days to go',
            'headline' => '100',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'golden_hour',
            'quote' => 'A hundred sunrises until you say I do — cherish the calm before the celebration.',
        ],
        '50' => [
            'label' => '50 days to go',
            'headline' => '50',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'garden_bloom',
            'quote' => 'Half a hundred days of butterflies, planning, and dreaming together.',
        ],
        '30' => [
            'label' => '30 days to go',
            'headline' => '30',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'midnight_rose',
            'quote' => 'The final month sparkles — your forever is almost here.',
        ],
        '15' => [
            'label' => '15 days to go',
            'headline' => '15',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'coastal_fog',
            'quote' => 'Two weeks of happy chaos, then a lifetime of quiet Sundays.',
        ],
        '10' => [
            'label' => '10 days to go',
            'headline' => 'Ten',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'saffron_edge',
            'quote' => 'A loving partner brings light to every day — their presence lifts your spirits and makes ordinary moments extraordinary.',
        ],
        '9' => [
            'label' => '9 days to go',
            'headline' => 'Nine',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'lavender_veil',
            'quote' => 'Single digits — hold hands a little tighter, laugh a little louder.',
        ],
        '8' => [
            'label' => '8 days to go',
            'headline' => 'Eight',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'cherry_romance',
            'quote' => 'Eight days until your favourite person becomes your family.',
        ],
        '7' => [
            'label' => '7 days to go',
            'headline' => 'Seven',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'ivory_script',
            'quote' => 'One week — the countdown feels like confetti in slow motion.',
        ],
        '6' => [
            'label' => '6 days to go',
            'headline' => 'Six',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'modern_mono',
            'quote' => 'Six sunsets left as fiancés — make each one count.',
        ],
        '5' => [
            'label' => '5 days to go',
            'headline' => 'Five',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'blush_arch',
            'quote' => 'Five days — breathe, smile, you’ve already chosen the best part: each other.',
        ],
        '4' => [
            'label' => '4 days to go',
            'headline' => 'Four',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'emerald_night',
            'quote' => 'Four days until the aisle, the vows, and the first dance.',
        ],
        '3' => [
            'label' => '3 days to go',
            'headline' => 'Three',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'sunset_warm',
            'quote' => 'Three — pack the joy, leave the stress, carry only love to the altar.',
        ],
        '2' => [
            'label' => '2 days to go',
            'headline' => 'Two',
            'headline_small' => null,
            'subline' => 'days to go',
            'theme' => 'royal_plum',
            'quote' => 'Forty-eight hours until forever gets its official beginning.',
        ],
        '1' => [
            'label' => '1 day to go',
            'headline' => 'One',
            'headline_small' => null,
            'subline' => 'day to go',
            'theme' => 'paper_minimal',
            'quote' => 'Tomorrow you marry your best friend — rest well, dream big.',
        ],
        'marriage_day' => [
            'label' => 'Marriage day',
            'headline' => 'Marriage',
            'headline_small' => 'day',
            'subline' => '',
            'theme' => 'celebration_gold',
            'quote' => 'Today is the day your hearts promised what they already knew — forever starts now.',
        ],
    ],
];
